# Site settings
title: Gray
email: johnotander@gmail.com
description: A grayscale color palette for prototyping the web.
baseurl: ""
url: "http://g-r-a-y-s-c-a-l-e.com"
twitter_username: 4lpine
github_username:  johnotander

# Build settings
markdown: kramdown
